server:
  port: 8761
  #port: 50021
eureka:
  datacenter: SDC
  environment: DEV1
  client:
    registerWithEureka: false
    fetchRegistry: false
    availabilityZones: 
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    #serviceUrl:
    #  defaultZone: http://localhost:8762/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0