spring:
  application:
    name: zuul
  jmx:
    enabled: false

server:
  port: 10000

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:2761/eureka/

  

  
    
zuul.sensitiveHeaders: Cookie,Set-Cookie
hystrix:
  command:
    default:
      execution:
          isolation:
             thread:
                timeoutInMilliseconds: 60000